### ISSUE TITLE
Yash Final Video

### ISSUE THREAD

**Issue by AD1616** [YashShah138/pigeonchestproject#5]
[Video](https://drive.google.com/file/d/1vatoOM9rxZrgly7C7DCeQwB9MDonNdDp/view?usp=sharing)
| Reviewing member| Scores from individuals|
| - | - |
| Erik |  5.5/6 |
| Sahil | 5.5/6  |
| Isaac | 5.5/6  |

**Comment by jm1021** [comment]
I watched video and it was nice to hear introduction.  However, as soon as you jumped to comments I would have like to know why you talked about comments in conjunction with your topic.   You talked about what the comments did in association with code but not the CB requirement.

Conditionals and rice quiz shared good work, but the entire connection was a little lost.   Some good work, but the video making and communication needs improvement.  5.25 of 6.   1.75/2 for comments.

**Comment by Nayanav** [comment]
Score:  
5.75/6

Goods: 
- I liked how you listed all the College Board topics. A lot of people missed that, shows your understanding (time: 0:05-0:15) 
![image](https://user-images.githubusercontent.com/34925114/140178587-f29b4d26-7da3-4ecd-a95b-f9587031dd86.png)



- Explanation of code is very detailed, it is evident that you understand the technical aspects of your project (time: 1:08) 
![image](https://user-images.githubusercontent.com/34925114/140178468-3e4afcbe-61e6-4957-8ef1-66bc532df389.png)



- Runtime was good, website working and running smoothly (time 2:13) 
![image](https://user-images.githubusercontent.com/34925114/140178290-9403633f-20c9-44bb-8662-25666b6c2687.png)

-Comments are detailed, I like how you mentioned them. Reinforces technical understanding (time: 0.:40).
![image](https://user-images.githubusercontent.com/34925114/140178721-9b3a59ed-2596-4e88-bc65-e52bb7a8d364.png)
 

 
Improvements: 
- There seems to be a little hesitation when explaining, no problem with that, just try to sound more confident as you know technicals really well 
- Maybe show different PBLs and mini-labs for each topic, shows a more variety of your work and input to the project in general
